@startuml

actor UR as "UN researcher"

rectangle Database

rectangle "Create a report of languages by population in (N)" {
    usecase UCG as "Get languages in (N)"
    usecase UCa as "Select (N)"
    usecase UCb as "Create report"

    UR - UCG
    UC8 <.. UCa : extend
    UCa ..> UCb : include
    UCG - Database
}

@enduml