@startuml

actor UR as "UN researcher"

rectangle Database

rectangle "Report List Country in the World - largest to smallest" {
    usecase UC8 as "Get countries by size - largest to smallest population"
    usecase UCa as "Select specific area"
    usecase UCb as "Create report"

    UR - UC8
    UC8 <.. UCa : extend
    UCa ..> UCb : include
    UC8 - Database
}

@enduml